### ISSUE TITLE
documentation  / howto

### ISSUE THREAD

**Issue by theetete** [lightbulb-framework/lightbulb-framework#1]
Hi,
I managed to install lightbulb but I'm now stuck on how to use it?
Do you have some step-by-step guidelines to setup and scan mod_security for example?

thanks

**Comment by istais** [comment]
Hello,
We are creating a documentation now, however it is not yet ready.
There is a number of examples included in the application folder, you can use them like this:

lightbulb < examples/test_difflearn_browser_waf_phpids.txt

You can extend the examples to include more tests. There is also a number of filters, regex sets and grammars in the data folder, which can be used for auditing the waf.

In order to have a significant performance boost, it is important to install openfst and it's python bindings (either pyfst or pywrapfst). The app will try to install this, however in some systems it may not be possible. We have tested this only in MacOS until now. If it is not installed, the python implementation will be used which is much more slow.

**Comment by theetete** [comment]
indeed, openfst not installed on my Centos7 system, seems not installed by Pypi :

```
Avaliable Modules:
Checking for pywrapfst module: FAIL
Checking for fst module: FAIL
Fallback to python implementation:OK
```

Otherwise, when I use your command I got:

```
Starting WebSocket Server at port 8000:  OK
Starting HTTP Server at port 8080:  OK
Please connect your Browser at http://localhost:8080
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/lightbulb/core/operate.py", line 77, in operate_diff_part
    initmodule = module(configuration, shared_memory, cross)
  File "/usr/lib/python2.7/site-packages/lightbulb/core/modules/sfadiff.py", line 69, in __init__
    self.mma = flex_object_m.yyparse(findlibrary(self.seed_file))
  File "/usr/lib/python2.7/site-packages/symautomata-0.0.4-py2.7.egg/symautomata/flex2fst.py", line 284, in yyparse
    mma = DFA(alphabet)
  File "/usr/lib/python2.7/site-packages/symautomata-0.0.4-py2.7.egg/symautomata/dfa.py", line 182, in __init__
    super(DFA, self).__init__(alphabet)
TypeError: must be type, not classobj

```

**Comment by istais** [comment]
Thanks for pointing out this issue. 

I think I fixed it in the symautomata version 0.0.5. Can you please update this to the latest version?

You can try to perform either "python install symautomata --upgrade" or "pip install -r requirements.txt" in the lightbulb framework folder

**Comment by theetete** [comment]
yes  symautomata version 0.0.5 fixed it. thanks

**Comment by LittleBobbyTable** [comment]
Hello,
I have lightbulb up and running. I wanted to try out your examples from the wiki and the folder, but I cant reach the given URLs ( http://83.212.105.5/PHPIDS07/ ) . So I want to know, are they just place holder and I need to get some WAF instances myself or am I doing something wrong?

**Comment by istais** [comment]
Yes, these are example WAFs. You should place the URL of your target there.

I usually maintain a number of WAFs deployed in this server for testing purposes, but currently it is not available.
