### ISSUE TITLE
Burp Extension can't be installed

### ISSUE THREAD

**Issue by HD421** [lightbulb-framework/lightbulb-framework#13]
I've cloned full repository and build it. All missed packages was downloaded, and my jython version is 2.7.0 But despite this I can not install an extension and got following error trace:

```
Traceback (most recent call last):
  File "/Users/igor/DevelPython/jython/lightBulb/lightbulb-framework/BurpExtension.py", line 44, in <module>
    from lightbulb.api.api import LightBulb
  File "/Users/igor/DevelPython/jython/lightBulb/lightbulb-framework/lightbulb/api/api.py", line 11, in <module>
    from cliff.app import App
ImportError: No module named cliff

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at lightbulb.api.api$py.f$0(/Users/igor/DevelPython/jython/lightBulb/lightbulb-framework/lightbulb/api/api.py:33)
	at lightbulb.api.api$py.call_function(/Users/igor/DevelPython/jython/lightBulb/lightbulb-framework/lightbulb/api/api.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx5.f$0(/Users/igor/DevelPython/jython/lightBulb/lightbulb-framework/BurpExtension.py:121)
	at org.python.pycode._pyx5.call_function(/Users/igor/DevelPython/jython/lightBulb/lightbulb-framework/BurpExtension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.f6e.<init>(Unknown Source)
	at burp.h2e.a(Unknown Source)
	at burp.mzg.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

P.S. i've installed module named cliff manually. It's doesn't solve my problem

**Comment by Hax0rG1rl** [comment]
The same here. 

Also, can you document a little more how the docker image should be used instead?

Thanks!

**Comment by ghost** [comment]
@Os3r3um  I also encountered the same mistakes are as follows


<img width="952" alt="default" src="https://user-images.githubusercontent.com/12621283/32567163-70c9081a-c4f5-11e7-8a73-6285bbbc012a.png">

**Comment by ghost** [comment]
@istais @sumanj @GeorgeArgyros @Os3r3um 
Please give comments
Thanks

**Comment by MuTouRend** [comment]
@istais @sumanj @GeorgeArgyros @Os3r3um 
Please give comments
Thanks

**Comment by istais** [comment]
Hello everyone,

- The problem that you encountered is related to a missing python package named cliff. Normally, you should first (1) install these requirements (as described in the installation of the lightbulb framework), second (2) point the "Folder for loading modules" option to the local python packages folder.

- If you try to do this solution and the problem remains, you can try to use the following standalone version which has all the requirements included:

[lightbulb-framework.zip](https://github.com/lightbulb-framework/lightbulb-framework/files/4853727/lightbulb-framework.zip)

Thanks


//Updated zip file with newer version

**Comment by istais** [comment]
Hello everyone,

- The problem that you encountered is related to a missing python package named cliff. Normally, if you should first (1) install these requirements (as described in the installation of the lightbulb framework), second (2) point the "Folder for loading modules" option to the local python packages folder.

- If you try to do this solution and the problem remains, you can try to use the following standalone version which has all the requirements included:

[lightbulb-framework.zip](https://github.com/lightbulb-framework/lightbulb-framework/files/1454993/lightbulb-framework.zip)

Thanks

**Comment by ghost** [comment]
@istais @sumanj @GeorgeArgyros @Os3r3um 
Please give comments
<img width="952" alt="1" src="https://user-images.githubusercontent.com/12621283/32568708-046a4d8c-c4fa-11e7-8653-b9bd45f0bc35.png">
<img width="952" alt="2" src="https://user-images.githubusercontent.com/12621283/32568718-0be37d86-c4fa-11e7-84c4-e042c68c31f3.png">
<img width="952" alt="3" src="https://user-images.githubusercontent.com/12621283/32568725-11903634-c4fa-11e7-93c5-85472796a3d3.png">

Thanks

**Comment by ghost** [comment]
<img width="952" alt="4" src="https://user-images.githubusercontent.com/12621283/32568954-b50916a0-c4fa-11e7-9ee6-850c70e8a991.png">

<img width="952" alt="1" src="https://user-images.githubusercontent.com/12621283/32568949-b0601180-c4fa-11e7-9c30-26e2d6825bdd.png">

**Comment by istais** [comment]
- In the first post, I cannot see the error. However, it would be better to try using the lightbulb framework in a Linux or MacOS platform in which it is more tested.

- In the second post, it is normal for these checks to fail, since these are the C bindings that are not required and the software can safely fall back to a pure python implementation.

Thanks

**Comment by Hax0rG1rl** [comment]
@istais Will try to make a short movie for you. I'm not sure my error was related to that cliff package though. I'm using Kali Linux so pb my issue should be more straight forward. 

Will have this a second try. On the other hand, you guys haven't provided a detailed description of how that docker image should be actually used in the context.

**Comment by ghost** [comment]
@istais 
Yes
pip install openfst
Tips need vc
I am testing to modify python's c extension for vc ++ 9.0 work because it wants to
Thank you very much for your reply
thanks

**Comment by istais** [comment]
@Os3r3um I had created the Dockerfile in the past, so it supports only the CLI version.
However, I just noticed that [it is possible](https://hub.docker.com/r/raesene/burp-free/~/dockerfile/) to run the burp suite in a docker instance. I think that it can be combined with the [old docker files](https://github.com/lightbulb-framework/lightbulb-framework/blob/master/docker/) in order to add support for GUI. I will check it out and maybe add this in the following days

**Comment by HD421** [comment]
Standalone version is good for me, thanks
