### ISSUE TITLE
BurpExtension error

### ISSUE THREAD

**Issue by kofa2002** [lightbulb-framework/lightbulb-framework#14]
raceback (most recent call last):
  File "/root/WeB-Attack/lightbulb-framework/BurpExtension.py", line 44, in <module>
    from lightbulb.api.api import LightBulb
  File "/root/WeB-Attack/lightbulb-framework/lightbulb/api/api.py", line 11, in <module>
    from cliff.app import App
ImportError: No module named cliff

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at lightbulb.api.api$py.f$0(/root/WeB-Attack/lightbulb-framework/lightbulb/api/api.py:33)
	at lightbulb.api.api$py.call_function(/root/WeB-Attack/lightbulb-framework/lightbulb/api/api.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromSource(imp.java:396)
	at org.python.core.imp.loadFromSource(imp.java:661)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx4.f$0(/root/WeB-Attack/lightbulb-framework/BurpExtension.py:121)
	at org.python.pycode._pyx4.call_function(/root/WeB-Attack/lightbulb-framework/BurpExtension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.g8c.<init>(Unknown Source)
	at burp.mde.a(Unknown Source)
	at burp.q9h.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sophron** [comment]
Please have a look at #13.
