### ISSUE TITLE
Error: Exception in thread Thread-8

### ISSUE THREAD

**Issue by forever-in18** [lightbulb-framework/lightbulb-framework#21]
Hi, when I use your command I got:

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lightbulb_framework-0.0.9-py2.7.egg/lightbulb/core/operate.py", line 77, in operate_diff_part
    initmodule = module(configuration, shared_memory, cross)
  File "/usr/local/lib/python2.7/dist-packages/lightbulb_framework-0.0.9-py2.7.egg/lightbulb/core/modules/sfadiff.py", line 38, in __init__
    self.setup(configuration)
  File "/usr/local/lib/python2.7/dist-packages/lightbulb_framework-0.0.9-py2.7.egg/lightbulb/core/base.py", line 41, in setup
    self.handler = handler_class(handler_configuration)
  File "/usr/local/lib/python2.7/dist-packages/lightbulb_framework-0.0.9-py2.7.egg/lightbulb/core/utils/browserhandler.py", line 108, in __init__
    self.host, self.wsport, SocketHandler)
  File "/usr/local/lib/python2.7/dist-packages/lightbulb_framework-0.0.9-py2.7.egg/lightbulb/core/utils/SimpleWebSocketServer.py", line 583, in __init__
    self.serversocket.bind((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

I use symautomata 0.0.12, but still not works.
very thank you to help me!

**Comment by istais** [comment]
Hello,

The important message is the following: "error: [Errno 98] Address already in use". It means that either you have another service running in this port, or there is a remaining process from a previous execution that is still using this port. 

I would recommend to either try to use a different port (select one that is not common), or just kill previous python processes - or just restart your system.

Let me know if the problem remains.

Best Regards,
Ioannis

**Comment by forever-in18** [comment]
Thank you so much!
But i run the example on a server, and the server don't have a browser. And when i run the example,I meet:
Please connect your Browser at http://localhost:8081
Please connect your Browser at http://localhost:8082
And i use the "curl  Browser at http://localhost:8081" command to connect it, it  returns 
<title>Fingerprint Test</title>
            <head>
            <script language="javascript" type="text/javascript">
              var x = 1;
              var changed = 0;

              window.onerror = function(msg, url) {
                 console.log(msg);
                 changed = 1;
                 return true;
              };

              function b64DecodeUnicode(str) {
                return decodeURIComponent(Array.prototype.map.call(atob(str), function(c) {
                return '%' + c.charCodeAt(0).toString(16);
                }).join(''));
              }
               var waitUntil = function (fn, condition, interval) {
                  interval = interval || 100;

                  var shell = function () {
                          var timer = setInterval(
                              function () {
                                  var check;

                                  try { check = !!(condition()); } catch (e) { check = false; }

                                  if (check) {
                                      clearInterval(timer);
                                      delete timer;
                                      fn();
                                  }
                              },
                              interval
                          );
                      };

                  return shell;
              };
              function doConnect()
              {
                websocket = new WebSocket("ws://localhost:8001/");
                websocket.onopen = function(evt) { websocket.send("INIT"); };
                websocket.onmessage = function(evt) { onMessage(evt) };
              }

              function onMessage(evt)
              {
                var text ='';
                if (evt.data instanceof Blob){
                  var reader = new FileReader();
                  reader.addEventListener("loadend", function() {
                      text=b64DecodeUnicode(reader.result);
                      writeToScreen(text);
                  });
                  reader.readAsText(evt.data);
                }else{
                  text=b64DecodeUnicode(reader.result);
                  writeToScreen(text);
                }
              }

              function a(){
                x=0;
              }

         function writeToScreen(message)
              {
                document.getElementById("output").innerHTML = "";
                x=1;
                changed=0;
                var vector = message;
                document.getElementById("output").innerHTML = "<img src=# onerror='changed=1'>"+vector;
                console.log(vector);
                var el =  document.getElementById("output").childNodes;
                if (el.length>1){
                    for (var k in el){
                      if (el[k] instanceof HTMLElement || el[k].nodeType > 0){
                        if ("onclick" in el[k]){
                          el[k].click();
                        }
                      }
                  }
                }
                waitUntil(
                  function () {
                    y = 0;
                    (function wait() {
                        if ( y ) {
                            console.log(x);websocket.send(x);
                        } else {
                             y =  y+1;
                            setTimeout( wait, '150' );
                        }
                    })();
                  },
                  function() {
                    return (changed==1);
                  },
                  10
                )();
              }
            </script>
            </head>
            <body onload="doConnect();">
            <div id="output" ></div>
            </body>
            </html>

it seems connect well.
But the example still stop on:
Please connect your Browser at http://localhost:8081
So what should i do ?
Thank you so much !

**Comment by istais** [comment]
You are probably conducting a differential test between two browsers, so you should navigate from e.g. Chrome in http://localhost:8081 and from Firefox in http://localhost:8082.

You can see the example here https://github.com/lightbulb-framework/lightbulb-framework/wiki/Differential-Testing:-Browser-and-Browser

There are also some examples here https://census.gr/news/2017/11/03/an-introduction-to-the-lightbulb-framework/ if you want to use the burp extension

**Comment by forever-in18** [comment]
But i run the example on a server without desktop, and it don't have a browser.
So i use the "curl  http://localhost:8081" command to connect it, but it doesn't work, still stop on :
Please connect your Browser at http://localhost:8081
So how should i do?

**Comment by istais** [comment]
It's not possible to perform differential test between two browsers, if you don't have two different browsers available to test. But you can try one of the other functionalities, like targeting a WAF
